services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    restart: always
    image: docker.elastic.co/kibana/kibana:8.5.1
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  etl:
    container_name: etl
    build:
      context: ./etl
      dockerfile: Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: on-failure
    env_file:
      - ./etl/.env
    volumes:
      - ./etl/data:/etl/data

volumes:
  esdata: