site_name: My Docs

nav:
  - Home: index.md
  - PIPELINE: pipeline.md
  - ETL: etl.md
  - BACK: back.md
  - FRONT: front.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      colors:
        primary: '#f5c518'
        accent: '#f5c518'
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      colors:
        primary: '#f5c518'
        accent: '#f5c518'

plugins:
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true